language: c

env:
  global:
    - OMP_NUM_THREADS=4
    # - secure: "encrypted environment variable"

compiler:
  - gcc

os:
  - linux
  # - osx

script:
  - cd lib/spookyhash/build
  # - sed -i.bak -e '37,40d' premake5.lua
  - ../../travis_build_premake.sh
  - ./premake5 gmake
  - make clean
  - ALL_CFLAGS+=-fPIC make
  - cd -
  # - ls -lahR ./lib/spookyhash/build/
  - make clean && make
