language: c

env:
  global:
    - OMP_NUM_THREADS=4
    # - secure: "encrypted environment variable"

compiler:
  - gcc

# OSX build failing; wait until you get access to a Mac
os:
  - linux
  # - osx

script:
  - cd lib/spookyhash/build
  - ../../travis_build_premake.sh
  - ./premake5 gmake
  - make clean
  - ALL_CFLAGS+=-fPIC make
  - cd -
  - make clean && make
